######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 17 00:18:32 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += my_player.h
FORMS += dlg_ctl.ui player.ui
SOURCES += main.cpp my_plyer.cpp
