#-------------------------------------------------
# gml2pic project file
#
# Do not edit this file!
# Edit gml2pic.config instead for defining file paths
# on your system.
#-------------------------------------------------


# includes the configuration file in which all required
# pathnames are defined
include(gml2pic.config)

# we build a Visual Studio on Windows, and a Makefile on other systems
win32 {
	TEMPLATE = vcapp
}
!win32 {
	TEMPLATE = app
}

# we build a console application
#CONFIG += console
# we want debug and release configurations
CONFIG += qt debug_and_release_target warn_on

# we also require the Qt's svg library
QT += svg

# link to ogdf library
win32 {
    CONFIG(debug, debug|release) {
        LIBS += $$OGDF_INSTALL_PATH/Win32/Debug/ogdf.lib
        DEFINES += OGDF_DEBUG
    } else {
        LIBS += $$OGDF_INSTALL_PATH/Win32/Release/ogdf.lib
    }
    LIBS += Psapi.lib
}

!win32 {
    CONFIG(debug, debug|release) {
        LIBS += $$OGDF_INSTALL_PATH/_debug/libOGDF.a
        DEFINES += OGDF_DEBUG
    } else {
        LIBS += $$OGDF_INSTALL_PATH/_release/libOGDF.a
    }
}



# add ogdf include path
INCLUDEPATH += $$OGDF_INSTALL_PATH


#-------------------------------------------------
# resource files
#-------------------------------------------------

# Windows
RC_FILE = gml2pic.rc

# Mac OS
ICON = gml2pic.icns


#-------------------------------------------------
# source files
#-------------------------------------------------

SOURCES += drawing-GML.cpp
SOURCES += drawing-OGML.cpp
SOURCES += EndpointShape.cpp
SOURCES += GMLProcessor.cpp
SOURCES += GraphProcessor.cpp
SOURCES += main.cpp
SOURCES += OGMLGraph.cpp
SOURCES += OGMLProcessor.cpp
SOURCES += shapes.cpp

HEADERS += EndpointShape.h
HEADERS += gml2pic.h
HEADERS += GMLProcessor.h
HEADERS += GraphProcessor.h
HEADERS += NodeShape.h
HEADERS += OGMLGraph.h
HEADERS += OGMLProcessor.h
