######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 17 19:41:33 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += dlg_sort.ui
